name: Build and Test

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Build
          run: cargo build
        - name: Clippy
          run: cargo clippy -- -Dwarnings -W clippy::pedantic -W clippy::nursery -W clippy::unwrap_used
        - name: Formatting
          run: cargo fmt --check

    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Run tests
          working-directory: ./tests
          run: cargo test

